### ISSUE TITLE
return CRT results mod{m*n}?

### ISSUE THREAD

**Issue by StefanKarpinski** [scheinerman/Mods.jl#15]
If I'm solving `CRT(Mod{m}(a), Mod{n}(b))` I currently get a non-modular integer. However, technically the solution is only unique modulo `m*n`. Should the result be an instance of `Mod{m*n}` instead of a non-modular integer? This also meshes the the natural recursive definition for more arguments, i.e. `CRT(a, b, c...) = CRT(CRT(a, b), c...)`.

**Comment by scheinerman** [comment]
Yes. That makes a lot of sense. I'll look into changing that.

**Comment by scheinerman** [comment]
@StefanKarpinski  When we calculate the `CRT` of (say) `Mod{n}(a)` and `Mod{m}(b)`, the modulus of the result is `n*m`. This can lead to a case where `n*m` is too large to fit in an `Int` or an `Int128`. Since we can't use a `BigInt` as a type parameter, errors will result. 

Thoughts?

For example:
```
julia> n = 12345
12345

julia> Mod{n}(12)
Mod{12345}(12)

julia> n = Int128(n)
12345

julia> Mod{n}(12)
Mod{12345}(12)

julia> n = big(n)
12345

julia> Mod{n}(12)
ERROR: TypeError: in Type, in parameter, expected Int64, got a value of type BigInt
```

**Comment by StefanKarpinski** [comment]
Yes, unfortunately one can run into that issue rather quickly with this type of usage.
