### ISSUE TITLE
inapproprate use of `adjoint`

### ISSUE THREAD

**Issue by KlausC** [scheinerman/Mods.jl#2]
I think, it is not a good idea to use the `adjoint` method to indicate the multiplicative inverse. That could prevent the use of possible generic matrix operations with `Mod` as element type. (If their implementation assumes `adjoint(x)` to mean "conjugate of x" applied to matrix elements x).
`adjoint` should fall back to `identity` for `Mod`.

**Comment by scheinerman** [comment]
This makes sense. I'm willing to remove it as it is redundant with `inv`. I can update the package, but I don't know how to release it under the new Julia package management system.

**Comment by KlausC** [comment]
>  ... but I don't know how to release it under the new Julia package management system


I prepared a `Project.toml`file, which you should add to the top directory of your package.
I assume, that Mods is located in .julia/dev (the standard place for packages under development).
First I renamed it because the procedure starts with empty. (`mv Mods Mods1`)
The initial release of the file was generated this way from the shell and julia REPL/package manager:
```
cd .jula/dev
]  # enter package manager prompt
generate Mods
<\backspace>
```
Afterwards I renamed and moved the file to the real Mods: (`mv Mods Mods2 && mv Mods1 Mods && mv Mods2/Project.toml Mods`)
Then I added information manually to the file until it looked like so: [Mods/Project.toml](https://gist.github.com/KlausC/a6dfef3c4b31c31185e09c672dc9253a)

If you need external packages or stdlib packages you can add them with the package manager:
```
cd .juli/dev
]
activate Mods
add LinearAlgebra
```
The changes are immediately written back to `Project.toml` of the activated package.
I think that is a first step towards releasing the package. I did not figure that out to the end.
see also [auto generate Project.toml](https://discourse.julialang.org/t/add-project-tomls-to-all-your-repos/23747)

**Comment by scheinerman** [comment]
Thanks for this.


On Jul 29, 2019, at 4:33 PM, Klaus Crusius <notifications@github.com<mailto:notifications@github.com>> wrote:


... but I don't know how to release it under the new Julia package management system

I prepared a Project.tomlfile, which you should add to the top directory of your package.
I assume, that Mods is located in .julia/dev (the standard place for packages under development).
First I renamed it because the procedure starts with empty. (mv Mods Mods1)
The initial release of the file was generated this way from the shell and julia REPL/package manager:

cd .jula/dev
]  # enter package manager prompt
generate Mods
<\backspace>


Afterwards I renamed and moved the file to the real Mods: (mv Mods Mods2 && mv Mods1 Mods && mv Mods2/Project.toml Mods)
Then I added information manually to the file until it looked like so: Mods/Project.toml<https://gist.github.com/KlausC/a6dfef3c4b31c31185e09c672dc9253a>

If you need external packages or stdlib packages you can add them with the package manager:

cd .juli/dev
]
activate Mods
add LinearAlgebra


The changes are immediately written back to Project.toml of the activated package.
I think that is a first step towards releasing the package. I did not figure that out to the end.
see also auto generate Project.toml<https://discourse.julialang.org/t/add-project-tomls-to-all-your-repos/23747>
